name: Fix executable bit

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/fix-executable.yml"

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set executable permission
        run: |
          chmod +x NoSQL/12-log_stats.py
          git rm .github/workflows/fix-executable.yml
          git config user.name "ghadi0alzhrani0"
          git config user.email "ghadi0alzhrani@gmail.com"
          git add NoSQL/12-log_stats.py
          git commit -m "12-log_stats.py"
          git push
